# Generated by Django 5.1.1 on 2024-10-21 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_key', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_key', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('pick_date', models.CharField(max_length=45)),
                ('item_type_count', models.IntegerField()),
                ('item_name', models.CharField(max_length=45)),
                ('user', models.ForeignKey(db_column='user_key', on_delete=django.db.models.deletion.CASCADE, to='easyList.user')),
            ],
            options={
                'db_table': 'post',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_key', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=45)),
                ('is_order', models.BooleanField()),
                ('post', models.ForeignKey(db_column='post_key', on_delete=django.db.models.deletion.CASCADE, to='easyList.post')),
                ('user', models.ForeignKey(db_column='user_key', on_delete=django.db.models.deletion.CASCADE, to='easyList.user')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type_num', models.IntegerField()),
                ('order_count', models.IntegerField()),
                ('is_picked', models.BooleanField(default=False)),
                ('remarks', models.CharField(max_length=45)),
                ('comment', models.ForeignKey(db_column='comment_key', on_delete=django.db.models.deletion.CASCADE, to='easyList.comment')),
            ],
            options={
                'db_table': 'order',
                'unique_together': {('comment', 'item_type_num')},
            },
        ),
    ]
